project 2 social links profile
poovanan-a/web-development-projects pull request #3
Opened 2024-05-25 07:35 UTC by poovanan-a

Hi Sudarshan! I have completed the second project, please have a look at it.

2024-05-27 12:51 UTC, sudarshanacharyaa requested changes
1.  **When zoomed out black container not expanding**
![image](https://github.com/poovanan-a/web-development-projects/assets/48318644/62ce20dd-92f6-4d28-a1c0-4511c61c2c76)

2. **Grey container height is equal to black container which is not looking good.**
![image](https://github.com/poovanan-a/web-development-projects/assets/48318644/df63a166-8481-4093-baa7-8a85be01ae95)

3.  **Buttons are not clickable and not able to visit the links of the website**
![image](https://github.com/poovanan-a/web-development-projects/assets/48318644/b42754a1-96a5-42f0-b7bb-0efb2c2e6097)

---------------------------------

CSS :

1. Styling in body element is not proper remove duplicates and unwanted styles
2. For all the website buttons code is repeating change it to one class and use that one everywhere.
3. Line 66 in style.css front-end class spelling error
------------------------------

HTML:
1. Instead of section give button element and add link to the websites for the button (anchor element and href for better understanding).

------------------------------------

Marks for code - 6/10 (good Improvement)

2024-05-27 13:00 UTC, poovanan-a commented
Thanks for the comment Sudarshan. Will modify accordingly and will get
back to you.



Regards,
Poovanan A
Contact Number : 9361457446

On Mon, 27 May 2024, 6:22 pm Sudarshan Pattabiraman, <
***@***.***> wrote:

> Assigned #3
> <https://github.com/poovanan-a/web-development-projects/pull/3> to
> @poovanan-a <https://github.com/poovanan-a>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/poovanan-a/web-development-projects/pull/3#event-12945661253>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVDOPN6HPMUPSIDTAFHLBHTZEMUAJAVCNFSM6AAAAABIIVWHT2VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSHE2DKNRWGEZDKMY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***
> .com>
>

2024-05-27 13:13 UTC, sudarshanacharyaa commented on social-link-profile/index.html
Tab Title is incorrect

2024-05-31 14:53 UTC, sudarshanacharyaa approved these changes

2024-05-31 14:54 UTC, merged